### ISSUE TITLE
[1.12.0] TypeError: char.charCodeAt is not a function

### ISSUE THREAD

**Issue by SOliveiraING** [ing-bank/vscode-psl#139]
After upgrading the plugin to 1.12.0 it I get the below error while test compiling.

[INFO][10:11:42]    … ⚙ MyCodeFile.psl TEST COMPILE in docker
[ERR!][10:11:42]    ❌ ⚙ error in docker TypeError: char.charCodeAt is not a function

Workaround revert to 1.11.4 version and the issue disappears.
